### ISSUE TITLE
`imandra-prelude` duplicated in vendor

### ISSUE THREAD

**Issue by hesterjeng** [imandra-ai/fix-engine#179]
I am not sure if this is something that is intended or not, but when installing the master branch, opam complains that there are too many copies of `imandra-prelude` vendored when attempting to install `fix-engine`.  This is because `fix-engine` vendors `imandra-prelude` and `imandra-ptime`, which itself vendors `imandra-prelude`.  I am making a pull request for this issue that removes the vendoring of `imandra-prelude` from `fix-engine`.  

Please let me know what you think or if there is a problem with my understanding of vendoring that caused me to hit this issue.

**Comment by Bronsa** [comment]
this is intended, we tend not to clone submodules recursively for vendored iml dependencies, instead we use a flattened vendoring
