### ISSUE TITLE
Reorganize `split_into_key_value` in Parser_utils

### ISSUE THREAD

**Issue by KKostya** [imandra-ai/fix-engine#87]
We still rely on some obscure `scanf` regexes to extract keys and values from the fields while parsing. Would be nice to implement the splitting more explicitly approach.
(Also not sure what to do if there are multiple `=` chars in the filed -- check the FIX specs.)

**Comment by ewenmaclean** [comment]
In my version I did I assumed the `=` was a special character in the FIX string and determined a valid segment - only happening once per segment. I think that's what the FIX specs say - I'll check, but I don't think you can use `=` elsewhere
