### ISSUE TITLE
Millisecond/microsecond timestamps?

### ISSUE THREAD

**Issue by KKostya** [imandra-ai/fix-engine#88]
Currently, we are treating the millisecond:
`20180531-11:39:25.885`
and microsecond:
`20180531-11:39:25.885332`
timestamps on the same footing using the same `fix_utctimestamp` and `fix_utctimeonly` types.
Potentially, that could be an issue if these two time-precisions get somehow mixed in a venue logic.

**Comment by ewenmaclean** [comment]
This is now dealt with in the `ewen/milliAndmicroForTimeDTs` branch and hooked up to ipl.

however this is still valid now:

https://github.com/AestheticIntegration/fix-engine/issues/92
